version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - STORAGE_SERVICE_URL=http://file-storage-service:8080/storage
      - ANALYSIS_SERVICE_URL=http://file-analysis-service:8080/analysis
    depends_on:
      - file-storage-service
      - file-analysis-service

  file-storage-service:
    build: ./file-storage-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/antiplagiat_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      postgres:
        condition: service_healthy

  file-analysis-service:
    build: ./file-analysis-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/antiplagiat_db
      - STORAGE_SERVICE_URL=http://file-storage-service:8080/storage
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=antiplagiat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d antiplagiat_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: